In [57]:
from sklearn.model_selection import train_test_split
import pandas as pd

In [58]:
feature_class = pd.read_csv('/Users/priyanshdesai07/Plaksha/MLPR/Project/YogaPal/feature_class.csv')

In [59]:
train_df, test_df = train_test_split(feature_class, test_size=0.2, random_state=42) 

In [60]:
train_df

f1          f2          f3          f4          f5          f6  \
916     1.215251  178.701795  160.780908  163.525199   45.808222   46.273112   
261    18.200794  165.186117  175.526671  142.298601    4.457796   84.511830   
607   155.079335  159.502772   15.871008   16.482777    8.133653    6.152547   
1331  175.251568    0.866504  132.838685  131.491195  179.465255    1.909601   
240    62.520758  124.881086   31.763892    0.235632  115.545881  179.343359   
...          ...         ...         ...         ...         ...         ...   
1130    9.507434  171.365004   18.399265  162.441225  144.322879   34.511114   
1294  173.429903   24.209763  130.057578  127.064989    3.657907  179.579783   
860   174.797692  176.906845   20.499403   18.538210   18.848601    7.770495   
1459  175.405444    1.614313  177.846870  174.312588  179.265651  178.057935   
1126   59.012702  118.835776   21.270091  158.445827  149.757344   26.540320   

              f7          f8          f9         f10         f11         f12  \
916    10.221909    9.778649  157.887718  166.323635  169.415868   18.959750   
261   125.215859   46.556846   25.884185  175.847411  165.962661  151.096085   
607   165.493384  151.505819   95.095715  166.015674  168.108538   33.614765   
1331  155.727521  143.300954   64.406778  166.432626  163.661625   13.109031   
240   151.331745   39.914026   59.353298   11.877250    5.107120  142.927908   
...          ...         ...         ...         ...         ...         ...   
1130  161.095602   17.817913   63.224838   14.239353  169.471597  169.913273   
1294  118.024926  148.850335   28.375701  164.403740  163.707278  176.758133   
860   160.309992   11.280125   44.518578  165.286435  176.749668   37.511165   
1459  153.701932   42.345202   73.455371  176.878066  174.203367   32.250924   
1126  156.782909   22.196073   60.858998   13.238733  170.059959  155.111662   

             f13         f14         f15  label  
916   130.278140  159.827422  157.418498      1  
261    18.015458  175.188548   11.506032      0  
607     0.374404   24.680920   24.744958      1  
1331  147.289609   84.031104   89.514661      2  
240    40.430047  169.410153    1.471897      0  
...          ...         ...         ...    ...  
1130    4.747327   15.602277  167.087285      3  
1294  145.793326   90.431421   76.210872      2  
860   144.540852   37.147992   33.015327      1  
1459  111.198382  175.112156  168.264229      2  
1126   27.852332   18.131835  162.020366      3  

[1605 rows x 16 columns]

In [61]:
test_df

f1          f2          f3          f4          f5          f6  \
1960  175.118997    0.048210  155.638956  156.817359   38.165912   40.165465   
526   174.895982  178.247573   23.558653   27.068620    5.794607    3.560919   
393    20.776743   21.886164  163.834368  164.476309  174.400376  165.532175   
1402  174.815875  172.560259  135.341165  134.833495    2.616912    2.960485   
433     2.990669    9.457863  156.513223  156.412224  176.617344  176.094287   
...          ...         ...         ...         ...         ...         ...   
938   178.110311  177.971681   15.410488   14.949850   14.223085   12.933281   
1326  172.343225  172.516179  126.855976  125.770005    2.433488    2.700150   
1138   35.093302  141.382119   18.347092  162.952727  160.231747   16.235959   
1037  149.799049   26.135202  145.989700   20.975982   30.125452  148.387807   
654     3.052402    3.483043  161.351132  159.755385  178.495228  172.127860   

              f7          f8          f9         f10         f11         f12  \
1960  163.972336  169.664597   71.105572  163.874026  165.593845  179.879761   
526   169.409627  172.080409   48.197755  169.375433  169.207910    3.198240   
393   168.368745    5.316406  122.069725   19.845749   21.754202  162.488441   
1402  157.999656  158.809840    0.222880  164.858100  165.269851    8.731413   
433   175.984970  177.264333  175.358181    4.858060    6.161580   22.489112   
...          ...         ...         ...         ...         ...         ...   
938     5.133310    2.416997  135.820531  166.042353  167.766301  158.430762   
1326  177.688772  163.482507   84.496017  162.627240  162.468923   18.878535   
1138  147.423155   32.272845   53.614488   13.567337  166.176058  166.744006   
1037   39.672071  143.255874  142.400825  167.309143   14.875696   68.457215   
654   162.759849    5.589880   97.999395   11.630663   12.108404   34.905954   

             f13         f14         f15  label  
1960  179.274196  157.197418  158.587304      5  
526   151.252671   38.128247   40.427285      1  
393   150.298751  158.001828  155.637952      1  
1402  172.068248   98.714861   97.882400      2  
433   154.994505  146.578357  145.050271      1  
...          ...         ...         ...    ...  
938   128.191435   29.028950   27.812121      1  
1326  172.149445   86.287612   88.149528      2  
1138   16.474721   21.386698  158.997489      3  
1037  136.717739  149.855623   27.000702      3  
654   151.582802  151.932284  146.718838      1  

[402 rows x 16 columns]

In [62]:
import torch 
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset

In [63]:
class SimpleNN(nn.Module):
    def __init__(self, input_size, hidden_size, num_classes):
        super(SimpleNN, self).__init__()
        self.fc1 = nn.Linear(input_size, hidden_size)
        self.relu1 = nn.ReLU()
        self.dropout = nn.Dropout(p=0.5)
        self.fc2 = nn.Linear(hidden_size, 50)
        self.relu2 = nn.ReLU()
        self.fc3 = nn.Linear(50, num_classes)
        self.softmax = nn.Softmax(dim=1)

    def forward(self, x):
        out = self.fc1(x)
        out = self.relu1(out)
        out = self.dropout(out)
        out = self.fc2(out)
        out = self.relu2(out)
        out = self.dropout(out)
        out = self.fc3(out)
        out = self.softmax(out)
        return out


In [64]:
input_size = 15  
hidden_size = 25
num_classes = 6  

model = SimpleNN(input_size, hidden_size, num_classes)

In [65]:
loss = nn.CrossEntropyLoss()
optimize = optim.Adam(model.parameters(), lr=0.001)


In [66]:
feature_torch = torch.tensor(train_df.drop('label',axis = 1).values, dtype=torch.float32)
label_torch = torch.tensor(train_df['label'].values,dtype=torch.int64)


In [67]:
feature_torch_test = torch.tensor(test_df.drop('label',axis = 1).values, dtype=torch.float32)
label_torch_test = torch.tensor(test_df['label'].values,dtype=torch.int64)

In [68]:
train_dataset = TensorDataset(feature_torch, label_torch)

In [69]:
test_dataset = TensorDataset(feature_torch_test, label_torch_test)

In [70]:
batch_size = 4
shuffle = True

train_loader = DataLoader(dataset=train_dataset, batch_size=batch_size, shuffle=shuffle)

In [71]:
batch_size = 4
shuffle = False   

test_loader = DataLoader(dataset=test_dataset, batch_size=batch_size, shuffle=shuffle)

In [72]:

def accurate(correct, total, pred, all_label):
    with torch.no_grad():
        for inputs, labels in test_loader:
            outputs = model(inputs)
            _, predicted = torch.max(outputs.data, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()
            pred.extend(predicted.cpu().numpy())
            all_label.extend(labels.cpu().numpy())
    
    return correct, total

    # accuracy = 100 * correct / total
    # print(f"Accuracy on the test data: {accuracy}%")

In [73]:
correct = 0
total = 0

pred = []
all_label = []

model.eval()


for epoch in range(20):
    # print(f"epoch: {epoch}/20")
    for inputs, labels in train_loader:
        
        optimize.zero_grad()  # Zero the gradients
        outputs = model(inputs)  # Forward pass
        loss1 = loss(outputs, labels)
        
        # Calculate loss
        loss1.backward()  # Backpropagation
        optimize.step()  # Update weights

correct1, total1 = accurate(correct, total, pred, all_label)
    
    # print('loss: ', loss1.item())
    # accuracy = 100 * correct1 / total1
    # print(f"Accuracy on the test data: {accuracy}%")

accuracy = 100 * correct1 / total1
print(f"Accuracy on the test data: {accuracy}%")

Accuracy on the test data: 80.34825870646766%


In [74]:
from sklearn.metrics import confusion_matrix, classification_report

In [75]:
conf_matrix = confusion_matrix(all_label, pred)

# Print the confusion matrix
print("Confusion Matrix:")
print(conf_matrix)

Confusion Matrix:
[[ 68   0   3   0   2   0]
 [  2 122   1   0   0   0]
 [  1   1  91   0   0   0]
 [ 37   3   1   0   0   0]
 [  0   2   3   0  27   1]
 [  7   2  11   0   2  15]]


In [76]:
class_report = classification_report(all_label, pred)
print("Classification Report:")
print(class_report)

Classification Report:
              precision    recall  f1-score   support

           0       0.59      0.93      0.72        73
           1       0.94      0.98      0.96       125
           2       0.83      0.98      0.90        93
           3       0.00      0.00      0.00        41
           4       0.87      0.82      0.84        33
           5       0.94      0.41      0.57        37

    accuracy                           0.80       402
   macro avg       0.69      0.68      0.66       402
weighted avg       0.75      0.80      0.76       402



/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_sta